apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - etcd-deployment.yaml
  - etcd-service.yaml
  - llama-stack-inference-model-secret.yaml
  - llama-stack-milvus-remote.yaml
  - llama-stack-milvus-secret.yaml
  - milvus-pvc.yaml
  - milvus-secret.yaml
  - milvus-service.yaml
  - milvus-standalone-deployment.yaml